#!/usr/bin/env python3
"""Rewrite the README roadmap from dev/PLAN.md.

    roadmap.py           rewrite the block between the roadmap markers in README.md
    roadmap.py --check   exit 1 when the block is out of date

A stage's progress is its closed steps over its listed steps; a stage marked done counts 100 %,
one without steps 0 %. The total is the mean over all stages. The current stage is the plan's
`Active:` one.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PLAN = ROOT / 'dev' / 'PLAN.md'
README = ROOT / 'README.md'
BEGIN, END = '<!-- roadmap:begin -->', '<!-- roadmap:end -->'

STAGE = re.compile(r'^## (S\d+) — (.+?)\s+\[([^\]]*)\]', re.M)
BAR_CELLS = 10


def stages(plan):
    """(number, title, progress 0..1) per stage, in plan order."""
    found = []
    heads = list(STAGE.finditer(plan))

    for i, head in enumerate(heads):
        body = plan[head.end():heads[i + 1].start() if i + 1 < len(heads) else len(plan)]
        steps = re.findall(rf'^- \[(.)\] {head.group(1)}\.\d+', body, re.M)
        done = head.group(3).strip().startswith('done')

        if done:
            progress = 1.0
        elif steps:
            progress = steps.count('x') / len(steps)
        else:
            progress = 0.0

        found.append((head.group(1), head.group(2), progress))

    return found


def bar(progress):
    filled = round(progress * BAR_CELLS)

    return '█' * filled + '░' * (BAR_CELLS - filled)


def render(plan):
    active = re.search(r'Active:\s*(S\d+)', plan)
    current = active.group(1) if active else None
    rows = stages(plan)
    total = sum(p for _, _, p in rows) / len(rows)
    percent = round(total * 100)

    badges = f'![Progress {percent}%](https://img.shields.io/badge/progress-{percent}%25-2ea44f.svg)'

    # "Active: none" between stages: no current-stage badge.
    if current is not None:
        badges += f' ![Current stage {current}](https://img.shields.io/badge/current%20stage-{current}-orange.svg)'

    lines = [
        BEGIN,
        badges,
        '',
        '| Stage | Progress | Done |',
        '|---|---|---:|',
    ]

    # No empty header cell: some renderers drop a table whose header has one.
    for number, title, progress in rows:
        if number == current:
            name = f'▶ **{number} · {title}**'
        else:
            name = f'{"✓ " if progress == 1.0 else ""}{number} · {title}'

        lines.append(f'| {name} | `{bar(progress)}` | {round(progress * 100)} % |')

    lines += ['', f'Total: **{percent} %**, the mean over {len(rows)} stages; a stage counts its closed steps in'
              ' [`dev/PLAN.md`](dev/PLAN.md). Generated by `tools/roadmap.py`.', END]

    return '\n'.join(lines)


def main():
    readme = README.read_text()
    begin, end = readme.index(BEGIN), readme.index(END) + len(END)
    updated = readme[:begin] + render(PLAN.read_text()) + readme[end:]

    if '--check' in sys.argv[1:]:
        if updated != readme:
            print('README roadmap is out of date: run tools/roadmap.py')
            return 1

        return 0

    README.write_text(updated)

    return 0


if __name__ == '__main__':
    sys.exit(main())
